services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: whackamole
      POSTGRES_USER: whackamole
      POSTGRES_PASSWORD: whackamole
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
